### ISSUE TITLE
multiline object types with indentation are not detected correctly

### ISSUE THREAD

**Issue by simonseyock** [jsdoctypeparser/jsdoctypeparser#132]
I was trying to use `eslint-plugin-jsdoc` for https://github.com/openlayers/openlayers

This multiline type is not recognized correctly:
```
   * @param {{includeWhiteSpace: (boolean|undefined),
   *    ignoreElementOrder: (boolean|undefined)}} [options] The options.
```

while this one is:
```
   * @param {{includeWhiteSpace: (boolean|undefined),
   * ignoreElementOrder: (boolean|undefined)}} [options] The options.
```

**Comment by brettz9** [comment]
Since it seems this is not a jsdoctypeparser issue since https://jsdoctypeparser.github.io/ shows no problems with the type contents, I think you actually might need to look to `eslint-plugin-jsdoc`.

However, this sounds like an issue that was fixed recently. Have you updated to the latest eslint-plugin-jsdoc to test?  If so, please provide your config and minimal test case (including the function context).

Thanks!

**Comment by brettz9** [comment]
Closing in favor of https://github.com/gajus/eslint-plugin-jsdoc/issues/686 and https://github.com/syavorsky/comment-parser/issues/121 . Thanks!
