### ISSUE TITLE
Variadic without an operand

### ISSUE THREAD

**Issue by brettz9** [jsdoctypeparser/jsdoctypeparser#89]
[An issue](https://github.com/gajus/eslint-plugin-jsdoc/issues/389) was reported on eslint-plugin-jsdoc which shows a case where valid parsing is returned, but an error encountered upon traversal.

The error occurs upon encountering the type, `function(...)`, which is expected to be equivalent to `function(...*)`.

This can be replicated with:

```js
const {parse, traverse} = require('./');

traverse(
  parse('function(...)')
);
```

The intermediate parsed structured looks like:

```js
  { type: 'FUNCTION',
  params: [ { type: 'VARIADIC', value: null, meta: { syntax: 'ONLY_DOTS' } } ],
  returns: null,
  this: null,
  new: null }
```

That is in contrast to other VARIADIC nodes which have had `params` objects with `value`, such as this:

```js
{ type: 'VARIADIC', value: { type: 'ANY' }, meta: { syntax: 'PREFIX_DOTS' }
```

I'm not sure whether we should fix `traverse` to allow or to actually prohibit this form. It is not entirely clear that this variadic format is considered acceptable or not (and if so by which jsdoc dialects).

- Closure does not make explicit mention of such a type: https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler ; though the jsdoctypeparser pegjs source points to a file using this format at [this line](https://github.com/google/closure-library/blob/47f9c92bb4c7de9a3d46f9921a427402910073fb/closure/goog/base.js#L1847)?), I'm not sure that this single example is authoritative.
- I'm not sure about TypeScript; seems there is an issue filed to add support for variadic in general--not sure about the empty format: https://github.com/microsoft/TypeScript/issues/5453
- vanilla jsdoc, whether at https://jsdoc.app/tags-type.html or https://jsdoc.app/tags-param.html do not make mention of such a type.
- JSDuck does not seem to support: https://github.com/senchalabs/jsduck/wiki/Type-Definitions

I would prefer to be more liberal (and allow this format in `traverse` as with `parse`) if there is some uncertainty, but just wanted to file an issue.

**Comment by sandersn** [comment]
I think this should be parsed even if no type checker supports it, because it makes life easier for linters that consume jsdoctypeparser. That said, I suspect it's not valid syntax in any type checker:

- Typescript does not support this format and does not parse it.
- I couldn't figure out if if Closure supports this format. I never got any errors in [an example program](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B...%257D%2520app%250A%2520*%252F%250Afunction%2520inferVoid(app)%2520%257B%250A%2520%2520%2520%2520return%2520app.concat(12)%250A%257D%250Awindow%255B'displayNoteTitle'%255D%2520%253D%2520inferVoid%253B%250AinferVoid(123)).... but I'm not sure I ever got the compiler service in a mode that reports errors.

I don't think we need jsduck support any more, although removing support would be unnecessary work.

**Comment by brettz9** [comment]
SGTM... And I've merged and updated devDeps. Do you think we could put out a release?

**Comment by sandersn** [comment]
5.1 sound good? The three changes I see are all additions. 

Here are the changes:
* allow typescript optional keys in literal types (Pelle Wessman)
* allow trailing commas in objects (ExE Boss)
* allow ... without trailing type (Brett Zamir)

**Comment by sandersn** [comment]
All right, 5.1 is published.

**Comment by brettz9** [comment]
Very sorry, but I've realized there needed to be a fix to `publish` as well. It's not needed for eslint-plugin-jsdoc, but I noticed it when applying to the source for https://jsdoctypeparser.github.io/ . I've pushed e45ea24ec947766221c5ab653a9702cacfb31d6a if you would be ok publishing a 5.1.1.

**Comment by sandersn** [comment]
5.1.1 is published!
